version: '3'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - .:/app/backend
    environment:
      - MONGO_URI=mongodb://db:27017/
    ports:
      - "3000:3000"
    networks:
      - app-network


volumes:
  db-data:

networks:
  app-network:
    driver: bridge
