version: '3'

services:
  #service for mongo
  db:
    # Pulling the image called "mongo"
    image: mongo
    # restart the container if it is already running
    restart: always
    # defines a volume named db-data
    volumes:
      - db-data:/data/db
    networks:
      - app-network

  backend:
    # fetching the image from my Docker Hub
    image: flyard/todo-backend
    depends_on: 
      - db
    volumes:
      - ./backend:/app/backend
    # Link to connect to mongo
    environment:
      - MONGO_URI=mongodb://db:27017/
    # Defining ports
    ports:
      - "3000:3000"
    networks:
      - app-network
    
  frontend:
    build: ./frontend
    depends_on: 
      - backend
    volumes:
    - type: bind
      source: ./frontend/src/components/cardList.jsx
      target: /app/src/components/cardList.jsx
    ports:
      - "5173:5173"
    networks:
      - app-network
# Using volumes
volumes:
  db-data:

networks:
  app-network:
    driver: bridge